/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface FileHashStorageInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "fileHashes"
      | "getFileHash"
      | "owner"
      | "removeFileHash"
      | "storeFileHash"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "fileHashes", values: [string]): string;
  encodeFunctionData(functionFragment: "getFileHash", values: [string]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "removeFileHash",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "storeFileHash",
    values: [string, string]
  ): string;

  decodeFunctionResult(functionFragment: "fileHashes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getFileHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeFileHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "storeFileHash",
    data: BytesLike
  ): Result;
}

export interface FileHashStorage extends BaseContract {
  connect(runner?: ContractRunner | null): FileHashStorage;
  waitForDeployment(): Promise<this>;

  interface: FileHashStorageInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  fileHashes: TypedContractMethod<[arg0: string], [string], "view">;

  getFileHash: TypedContractMethod<[filename: string], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  removeFileHash: TypedContractMethod<[filename: string], [void], "nonpayable">;

  storeFileHash: TypedContractMethod<
    [filename: string, hash: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "fileHashes"
  ): TypedContractMethod<[arg0: string], [string], "view">;
  getFunction(
    nameOrSignature: "getFileHash"
  ): TypedContractMethod<[filename: string], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "removeFileHash"
  ): TypedContractMethod<[filename: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "storeFileHash"
  ): TypedContractMethod<
    [filename: string, hash: string],
    [void],
    "nonpayable"
  >;

  filters: {};
}
